// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/input-output-hk/cicero/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// EvaluationService is an autogenerated mock type for the EvaluationService type
type EvaluationService struct {
	mock.Mock
}

// EvaluateWorkflow provides a mock function with given fields: src, name, id, inputs
func (_m *EvaluationService) EvaluateWorkflow(src string, name string, id uint64, inputs domain.Facts) (domain.WorkflowDefinition, error) {
	ret := _m.Called(src, name, id, inputs)

	var r0 domain.WorkflowDefinition
	if rf, ok := ret.Get(0).(func(string, string, uint64, domain.Facts) domain.WorkflowDefinition); ok {
		r0 = rf(src, name, id, inputs)
	} else {
		r0 = ret.Get(0).(domain.WorkflowDefinition)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, uint64, domain.Facts) error); ok {
		r1 = rf(src, name, id, inputs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkflows provides a mock function with given fields: src
func (_m *EvaluationService) ListWorkflows(src string) ([]string, error) {
	ret := _m.Called(src)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
