// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/nomad/api"
	domain "github.com/input-output-hk/cicero/src/domain"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"
)

// NomadEventService is an autogenerated mock type for the NomadEventService type
type NomadEventService struct {
	mock.Mock
}

// GetEventAllocByWorkflowId provides a mock function with given fields: _a0
func (_m *NomadEventService) GetEventAllocByWorkflowId(_a0 uint64) (map[string]domain.AllocWrapper, error) {
	ret := _m.Called(_a0)

	var r0 map[string]domain.AllocWrapper
	if rf, ok := ret.Get(0).(func(uint64) map[string]domain.AllocWrapper); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.AllocWrapper)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastNomadEvent provides a mock function with given fields:
func (_m *NomadEventService) GetLastNomadEvent() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *NomadEventService) Save(_a0 pgx.Tx, _a1 *api.Event) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, *api.Event) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
