// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/input-output-hk/cicero/src/domain"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"

	uuid "github.com/google/uuid"
)

// ActionRepository is an autogenerated mock type for the ActionRepository type
type ActionRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *ActionRepository) GetAll() ([]*domain.Action, error) {
	ret := _m.Called()

	var r0 []*domain.Action
	if rf, ok := ret.Get(0).(func() []*domain.Action); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Action)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0
func (_m *ActionRepository) GetById(_a0 uuid.UUID) (domain.Action, error) {
	ret := _m.Called(_a0)

	var r0 domain.Action
	if rf, ok := ret.Get(0).(func(uuid.UUID) domain.Action); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Action)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrent provides a mock function with given fields: _a0
func (_m *ActionRepository) GetCurrent(_a0 pgx.Tx) ([]*domain.Action, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Action
	if rf, ok := ret.Get(0).(func(pgx.Tx) []*domain.Action); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Action)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(pgx.Tx) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestByName provides a mock function with given fields: _a0
func (_m *ActionRepository) GetLatestByName(_a0 string) (domain.Action, error) {
	ret := _m.Called(_a0)

	var r0 domain.Action
	if rf, ok := ret.Get(0).(func(string) domain.Action); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Action)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *ActionRepository) Save(_a0 pgx.Tx, _a1 *domain.Action) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, *domain.Action) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
