// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	liftbridge "github.com/liftbridge-io/go-liftbridge/v2"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"
)

// MessageQueueRepository is an autogenerated mock type for the MessageQueueRepository type
type MessageQueueRepository struct {
	mock.Mock
}

// GetOffset provides a mock function with given fields: _a0
func (_m *MessageQueueRepository) GetOffset(_a0 string) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0, _a1, _a2
func (_m *MessageQueueRepository) Save(_a0 pgx.Tx, _a1 map[string][]byte, _a2 *liftbridge.Message) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, map[string][]byte, *liftbridge.Message) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
