// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/input-output-hk/cicero/src/domain"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"

	uuid "github.com/google/uuid"
)

// RunService is an autogenerated mock type for the RunService type
type RunService struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *RunService) GetAll() ([]*domain.Run, error) {
	ret := _m.Called()

	var r0 []*domain.Run
	if rf, ok := ret.Get(0).(func() []*domain.Run); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByActionId provides a mock function with given fields: _a0
func (_m *RunService) GetByActionId(_a0 uuid.UUID) ([]*domain.Run, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Run
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*domain.Run); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Run)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNomadJobId provides a mock function with given fields: _a0
func (_m *RunService) GetByNomadJobId(_a0 uuid.UUID) (domain.Run, error) {
	ret := _m.Called(_a0)

	var r0 domain.Run
	if rf, ok := ret.Get(0).(func(uuid.UUID) domain.Run); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Run)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JobLogs provides a mock function with given fields: _a0
func (_m *RunService) JobLogs(_a0 uuid.UUID) (*domain.LokiOutput, error) {
	ret := _m.Called(_a0)

	var r0 *domain.LokiOutput
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.LokiOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LokiOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunLogs provides a mock function with given fields: allocId, taskGroup
func (_m *RunService) RunLogs(allocId string, taskGroup string) (*domain.LokiOutput, error) {
	ret := _m.Called(allocId, taskGroup)

	var r0 *domain.LokiOutput
	if rf, ok := ret.Get(0).(func(string, string) *domain.LokiOutput); ok {
		r0 = rf(allocId, taskGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LokiOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(allocId, taskGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *RunService) Save(_a0 pgx.Tx, _a1 *domain.Run) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, *domain.Run) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *RunService) Update(_a0 pgx.Tx, _a1 *domain.Run) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, *domain.Run) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
